services:
    mysql:
        image: mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: 'dummy'
        healthcheck:
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
        volumes:
            - ./mysql-dump:/docker-entrypoint-initdb.d
        ports: 
            - 3307:3306
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
    node:
        image: alpine-